# Generated by Django 5.0.6 on 2024-05-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to=None)),
                ('Name', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Ingrdients', models.CharField(max_length=100)),
                ('Process', models.TextField()),
            ],
        ),
    ]
