# Generated by Django 5.0.6 on 2024-05-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingrdients',
            new_name='ingrdients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Process',
            new_name='process',
        ),
    ]
