# Generated by Django 5.0.6 on 2024-05-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_category_recipe_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrdients',
            new_name='ingredients',
        ),
    ]
